"""Content for the four newer advice guides. Rendered by more_guides() in build.py."""

REJECTED = {
    "key": "a-rejected.html",
    "title": "Insurance Claim Rejected? What to Do Next | Independent Claims Consultants",
    "desc": "Insurance claim rejected or reduced? Why it happens, how to challenge the decision, the complaints process and the Financial Ombudsman Service.",
    "h1": "Insurance claim rejected? <span>Here's what to do</span>",
    "lead": "A rejection letter isn't always the final word. Here's why claims are turned down, how to challenge the decision and where to go if your insurer won't move.",
    "image": ("phone-woman", "A woman in an office talking on the telephone"),
    "intro_eyebrow": "Why it happens",
    "intro_head": "Why insurers reject or reduce claims",
    "intro": [
        "Your policy is a contract. An insurer can turn a claim down if it believes the loss isn't covered, you haven't kept to a condition of the policy, or something wasn't disclosed when you took the cover out.",
        "That doesn't mean the insurer is right. Decisions are often based on the loss adjuster's report, and that report is written from the insurer's point of view. Exclusions can be applied too widely, and evidence can be missed or misread.",
        "Read the decision letter carefully. It should tell you which part of the policy the insurer is relying on. That's the starting point for any challenge.",
    ],
    "reasons_head": "Common reasons we see",
    "reasons": [
        ("Wear and tear or gradual damage", "Often used for storm, roof and escape of water claims. It can be challenged when the event, not age, caused the damage."),
        ("An exclusion in the policy", "Such as unoccupancy, flood in some policies, or poor workmanship. The exact wording matters."),
        ("Non-disclosure", "The insurer says something wasn't declared when you bought the policy. It must usually show it would have made a difference."),
        ("Breach of a condition", "For example, alarm or security requirements. Whether the breach had anything to do with the loss can be important."),
        ("Not enough evidence", "Missing proof of ownership or of what happened. This can often be put right."),
        ("Underinsurance", "A claim reduced because the sum insured was too low. The calculation is worth checking."),
    ],
    "steps_head": "How to challenge the decision",
    "steps_intro": "Act promptly and keep everything in writing.",
    "steps": [
        ("Ask for the reasons in writing", "Request the policy wording relied on, and a copy of the loss adjuster's report or the key findings."),
        ("Check the policy wording", "Compare the reasons with the exact wording of the cover, exclusions and conditions in your policy."),
        ("Gather your evidence", "Photos, reports, receipts, emails and any expert opinions that support your version of events."),
        ("Make a formal complaint", "Tell the insurer you want your complaint dealt with under its complaints procedure."),
        ("Wait for the final response", "Insurers generally have eight weeks to send a final response to a complaint."),
        ("Go to the Financial Ombudsman Service", "If you're unhappy with the final response, or don't get one within eight weeks, you can refer it to the ombudsman."),
    ],
    "fos_head": "The Financial Ombudsman Service",
    "fos": [
        "The Financial Ombudsman Service settles disputes between consumers and financial businesses, including insurers. It's free to use for consumers and many small businesses.",
        "You generally need to refer your complaint within six months of the insurer's final response, so don't leave it too long. The final response letter should explain your right to refer it.",
        "The ombudsman looks at what's fair and reasonable in the circumstances, not just the strict wording of the policy.",
    ],
    "help_head": "How we can help",
    "help": [
        "We've been challenging insurers' decisions for over 30 years. We'll review the decision, the policy and the loss adjuster's findings, and tell you honestly whether we think it can be overturned.",
        "If it can, we'll build the case and negotiate with your insurer for you. Your first consultation is free and we work on a no win, no fee basis.",
    ],
    "faqs": [
        ("Can my insurer reject my claim?",
         "<p>In some circumstances, yes. An insurer can turn a claim down if the loss isn't covered, a policy condition hasn't been met, or it suspects fraud. But insurers can get it wrong, and many decisions can be challenged.</p>"),
        ("How long do I have to complain?",
         "<p>Complain to your insurer as soon as you can. If you then want to go to the Financial Ombudsman Service, you generally need to do so within six months of the insurer's final response.</p>"),
        ("Does it cost anything to go to the ombudsman?",
         "<p>No. The Financial Ombudsman Service is free for consumers and many small businesses.</p>"),
        ("Can a loss assessor help after a claim has been rejected?",
         "<p>Yes. We regularly take on claims that have been rejected or reduced. We'll look at the decision and the evidence and give you an honest view of your chances before you commit to anything.</p>"),
    ],
    "related": ["a-vs.html", "a-under.html", "a-questions.html"],
}

COST = {
    "key": "a-cost.html",
    "title": "How Much Does a Loss Assessor Cost? | Independent Claims Consultants",
    "desc": "How loss assessor fees work in the UK, what no win, no fee means, when it's worth appointing a loss assessor and what you get for the fee.",
    "h1": "How much does a <span>loss assessor cost?</span>",
    "lead": "Most people worry about the fee before they pick up the phone. Here's how loss assessor fees usually work, and how to decide whether it's worth it for your claim.",
    "image": ("homeowner-woman", "A smiling woman sitting at her laptop at home"),
    "intro_eyebrow": "How fees work",
    "intro_head": "How loss assessors are paid",
    "intro": [
        "A loss assessor's fee is usually a percentage of the final settlement, agreed with you in writing before any work starts. The percentage can vary with the size and complexity of the claim.",
        "Because the fee comes out of the settlement, you normally don't pay anything upfront. The aim is that our work increases the settlement by more than the cost of our fee.",
        "At Independent Claims Consultants, your first consultation is free and there's no obligation. We work on a no win, no fee basis, so we don't get paid until you do. We'll explain how our fee works for your claim before you agree to anything.",
    ],
    "reasons_head": "What the fee covers",
    "reasons": [
        ("A dedicated loss assessor", "One expert manages your claim from first visit to final settlement."),
        ("Emergency help", "Securing the property, organising emergency works and arranging alternative accommodation where needed."),
        ("A full assessment", "Identifying the full extent of the damage to your buildings and contents, including what's easy to miss."),
        ("Preparing and negotiating", "Presenting your whole claim and dealing with your insurer and its loss adjuster for you."),
        ("Specialist support", "Legal specialists and forensic and consequential loss accountants where a claim needs them."),
        ("Overseeing the repairs", "Helping you appoint surveyors and contractors, and supervising the work to completion."),
    ],
    "steps_head": "Questions to ask any loss assessor",
    "steps_intro": "Whoever you choose, get clear answers before you sign.",
    "steps": [
        ("What is the fee, and how is it worked out?", "Make sure you know the percentage and what it's calculated on."),
        ("What happens if the claim isn't successful?", "With no win, no fee, you shouldn't owe a fee if there's no settlement."),
        ("Who will handle my claim?", "Ask whether you'll have one named person from start to finish."),
        ("Are you regulated?", "Claims management is regulated by the Financial Conduct Authority. You can check the FCA register."),
        ("Are you members of a professional body?", "Such as the Institute of Public Loss Assessors."),
        ("Can I cancel?", "Ask what the cancellation terms are, and get everything in writing."),
    ],
    "fos_head": "Is it worth it?",
    "fos": [
        "For a small, simple claim that your insurer is handling well, you may not need a loss assessor at all. We'll tell you if we think that's the case.",
        "It's usually worth it when the damage is serious, the claim is complicated, you've been displaced from your home or business, or the insurer is disputing or reducing the claim. In those cases, people often don't know everything they can claim for.",
        "It also saves you time and stress. Managing a major claim can feel like a full-time job while you're trying to get back to normal.",
    ],
    "help_head": "Talk to us first",
    "help": [
        "Call us for a free, no-obligation chat about your claim. We'll give you an honest view of whether we can add value, and explain our fee clearly before you decide.",
    ],
    "faqs": [
        ("How much do loss assessors charge?",
         "<p>Fees are usually a percentage of the final settlement, agreed in advance. The percentage can vary depending on the size and complexity of the claim. We'll explain our fee for your claim during your free consultation.</p>"),
        ("Do I have to pay anything upfront?",
         "<p>Not with us. Your first consultation is free and we work on a no win, no fee basis, so we don't get paid until you do.</p>"),
        ("Doesn't my insurer's loss adjuster do this for free?",
         "<p>A loss adjuster is appointed and paid by your insurer and works on its behalf. A loss assessor is appointed by you and works only for you. <a href=\"a-vs.html\">Read more about the difference</a>.</p>"),
        ("Will appointing a loss assessor upset my insurer?",
         "<p>No. Appointing your own representation is common, and it's your right. Having a professional present your claim can make the process smoother for everyone.</p>"),
    ],
    "related": ["a-vs.html", "a-rejected.html", "a-timeline.html"],
}

ACCOMMODATION = {
    "key": "a-accommodation.html",
    "title": "Alternative Accommodation After a Fire or Flood | ICC Loss Assessors",
    "desc": "Can't live at home after a fire, flood or leak? What alternative accommodation your home insurance may cover, how it's arranged and how to protect your claim.",
    "h1": "Alternative accommodation <span>after a fire or flood</span>",
    "lead": "If fire, flood or a major leak leaves your home unfit to live in, your policy may pay for somewhere else to stay. Here's how it usually works.",
    "image": ("landlord-flats", "A row of terraced houses on a London street"),
    "intro_eyebrow": "Your cover",
    "intro_head": "What your policy may pay for",
    "intro": [
        "Most home insurance policies include cover for alternative accommodation if your home can't be lived in after an insured event. It's often found under the buildings section, the contents section, or both.",
        "There's usually a limit. It may be a fixed amount or a percentage of your sum insured, so check your policy schedule and wording.",
        "The aim is to put you in similar accommodation to what you had, close enough for work and school, for as long as the repairs reasonably take.",
    ],
    "reasons_head": "Types of accommodation",
    "reasons": [
        ("A hotel or B&amp;B", "Often used for the first few nights while longer-term options are found."),
        ("A rented house or flat", "Usually the best option for longer repairs, especially for families."),
        ("Serviced apartments", "Useful when you need somewhere furnished at short notice."),
        ("A caravan or mobile home", "Sometimes placed on your own property so you can stay close by."),
        ("Pets and animals", "Some policies include kennel or cattery costs. Check what yours says."),
        ("Extra costs", "Such as additional travel or storage. Your insurer may deduct costs you no longer pay, like some household bills."),
    ],
    "steps_head": "How to protect your claim",
    "steps_intro": "Getting this right early makes a big difference to your family.",
    "steps": [
        ("Tell your insurer straight away", "Explain that the property can't be lived in and ask about alternative accommodation."),
        ("Agree it before you commit", "Get the insurer's agreement before signing a tenancy or booking anything long-term."),
        ("Think about your needs", "School runs, work, health, pets and anyone with mobility needs should all be considered."),
        ("Keep every receipt", "Record any extra costs, such as fuel, laundry, meals out or storage."),
        ("Plan for the long term", "Drying and rebuilding can take months. Make sure the arrangement can be extended if needed."),
        ("Get help", "A loss assessor can arrange and negotiate the accommodation for you."),
    ],
    "fos_head": "Landlords and tenants",
    "fos": [
        "If you're a landlord, your tenant's alternative accommodation is usually their responsibility, often through their own contents insurance. Your own policy may include loss of rent cover for the rent you lose while the property can't be let.",
        "If you're a tenant, check your contents policy. Your landlord's buildings insurance doesn't usually cover your belongings or where you stay.",
    ],
    "help_head": "How we can help",
    "help": [
        "Arranging alternative accommodation is one of the first things we do after a serious fire or flood. We'll help find somewhere suitable, agree it with your insurer and make sure the costs are covered for as long as the work takes.",
    ],
    "faqs": [
        ("Will my home insurance pay for a hotel?",
         "<p>If your home can't be lived in after an insured event, most policies will pay for reasonable alternative accommodation, which can include a hotel for the first few nights. There's usually a limit, so check your policy.</p>"),
        ("How long will alternative accommodation be paid for?",
         "<p>Usually for as long as it reasonably takes to make your home habitable again, up to the policy limit. After a major fire or flood, that can be several months.</p>"),
        ("Do I have to use the accommodation my insurer suggests?",
         "<p>It has to be suitable for your household. If what's offered doesn't meet your needs, for example it's too far from school or work, raise it with your insurer. We can negotiate this for you.</p>"),
        ("Can you arrange accommodation for me?",
         "<p>Yes. If you appoint us early, we can arrange alternative accommodation where it's needed and deal with your insurer about the cost.</p>"),
    ],
    "related": ["a-fire.html", "a-flood.html", "a-timeline.html"],
}

TIMELINE = {
    "key": "a-timeline.html",
    "title": "How Long Does an Insurance Claim Take? | Independent Claims Consultants",
    "desc": "How long home and business insurance claims take in the UK, the stages of a property claim, what causes delays and how to keep your claim moving.",
    "h1": "How long does an <span>insurance claim take?</span>",
    "lead": "There's no set timescale, but knowing the stages helps you plan, and spot when a claim is stalling.",
    "image": ("repairs-plaster", "A decorator preparing a wall during repairs"),
    "intro_eyebrow": "The short answer",
    "intro_head": "It depends on the claim",
    "intro": [
        "Every claim is different. In our experience, a straightforward, non-contentious claim generally takes between four and six weeks to settle.",
        "Larger claims take longer. A serious fire or flood can involve drying, specialist reports and rebuilding, and a business interruption claim may run for as long as the business takes to recover.",
        "We don't get paid until you do, so we progress every claim as quickly and forcefully as we can.",
    ],
    "reasons_head": "What slows a claim down",
    "reasons": [
        ("Disputes over cover", "If the insurer questions whether the loss is covered, the claim can stall until it's resolved."),
        ("Drying out", "After water damage, repairs shouldn't start until the building is dry, which can take weeks."),
        ("Missing information", "Gaps in evidence, photos or proof of ownership lead to back-and-forth."),
        ("Underinsurance", "Disagreements over the sum insured can hold up a settlement."),
        ("Specialist reports", "Structural, electrical or forensic reports add time, but are sometimes essential."),
        ("Contractor availability", "After widespread floods or storms, trades and materials can be in short supply."),
    ],
    "steps_head": "The stages of a property claim",
    "steps_intro": "Most home and business claims follow the same broad path.",
    "steps": [
        ("Report the claim", "Tell your insurer as soon as you can, and make the property safe."),
        ("Emergency works", "Securing the building, stopping further damage and arranging alternative accommodation if needed."),
        ("Investigation", "The insurer may appoint a loss adjuster to visit and look into the cause of the loss."),
        ("Liability decision", "The insurer confirms whether the claim is covered under the policy."),
        ("Scope and costs", "The damage is measured, drying is monitored and repair costs and contents losses are calculated."),
        ("Negotiation and settlement", "The claim is agreed and paid, either in stages or in full, and the repairs are completed."),
    ],
    "fos_head": "How to keep your claim moving",
    "fos": [
        "Report the claim promptly, keep a record of every call and email, and send information as soon as it's asked for.",
        "Take photos and videos of all the damage before anything is cleared away, and keep damaged items until your insurer agrees they can go.",
        "If you're out of pocket while the claim is ongoing, ask whether an interim payment is possible.",
        "Appoint a loss assessor early. We'll have everything in place, ready for the moment liability is accepted.",
    ],
    "help_head": "How we can help",
    "help": [
        "If your claim has stalled, or you'd rather someone else kept it moving, call us. Your first consultation is free and we work on a no win, no fee basis.",
    ],
    "faqs": [
        ("How long does a home insurance claim take?",
         "<p>A straightforward, non-contentious claim generally takes between four and six weeks to settle. Larger or disputed claims, such as a major fire or flood, can take considerably longer.</p>"),
        ("Why is my insurance claim taking so long?",
         "<p>Common causes include disputes over cover, drying out after water damage, missing information and waiting for specialist reports. If your claim has stalled, we can help.</p>"),
        ("Can I get an interim payment?",
         "<p>On larger claims, insurers can sometimes make interim payments once liability is accepted, so you're not left out of pocket. It's worth asking.</p>"),
        ("Does a loss assessor make a claim take longer?",
         "<p>No. Our aim is to settle your claim as quickly as possible. We don't get paid until you do, so we have every reason to keep it moving.</p>"),
    ],
    "related": ["a-accommodation.html", "a-cost.html", "a-questions.html"],
}

GUIDES = [REJECTED, COST, ACCOMMODATION, TIMELINE]
