"""Content for the claim-type and audience pages.

Facts about the firm come from the original independentclaimsconsultants.com site.
Everything else is general guidance about UK property insurance claims; wording such as
"depending on your policy" is deliberate, because cover varies between insurers.
"""

# Indexes into CASES in build.py
FACTORY_FIRE, MULTI_TENANCY_FIRE, RETAIL_FLOOD, HOUSE_FIRE = 0, 1, 2, 3

QUICK = [
    ("Free assessment", "No obligation, no upfront cost"),
    ("No win, no fee", "We don't get paid until you do"),
    ("Your own loss assessor", "From first call to final settlement"),
]

SERVICE_PAGES = [
    # ------------------------------------------------------------------ fire
    {
        "key": "fire.html",
        "route": "fire-damage-claims/",
        "crumb": "Fire damage claims",
        "title": "Fire Damage Insurance Claims | Independent Claims Consultants",
        "desc": "Loss assessors for fire damage claims. We manage your home or business fire insurance claim, including smoke, soot and water damage. No win, no fee.",
        "pill": "Fire damage claims",
        "h1": "Fire damage <span>insurance claims</span>",
        "lead": "A fire at your home or business is devastating. Our loss assessors take over your fire insurance claim, so you can focus on your family or your business while we fight for your full entitlement.",
        "image": ("fire-damage", "A man sitting in a fire-damaged living room"),
        "claim": "Fire or smoke damage",
        "service_type": "Fire damage insurance claims",
        "icon": "fire",
        "intro_head": "Every decision after a fire affects your claim",
        "intro": [
            "Following a fire you will have to make a number of critical decisions, and each one has a direct impact on the outcome of your insurance claim. What can be saved, who carries out the work, where you stay in the meantime and what you sign all matter.",
            "Your insurer will appoint a loss adjuster to assess the claim on its behalf. With Independent Claims Consultants on your side, you have your own expert too: a dedicated loss assessor who guides you through the entire fire claims process and makes sure you understand your options at every stage.",
            "Fire damage is rarely limited to what burned. Smoke and soot travel through a building, and the water used to put the fire out can cause damage of its own. We make sure all of it is found, documented and included in your claim.",
        ],
        "help_head": "How we help with your fire claim",
        "help": [
            ("shield", "Make the property safe", "We organise emergency works such as boarding up and securing the building."),
            ("home", "Somewhere to stay", "We arrange alternative accommodation while your home is put right, where your policy covers it."),
            ("file", "The full extent of the damage", "Fire, smoke, soot and firefighting water damage to both buildings and contents."),
            ("scale", "Deal with the insurer", "We handle the loss adjuster and any investigators, and negotiate your settlement."),
            ("tool", "Oversee the repairs", "We help appoint specialist contractors and supervise the work through to completion."),
            ("trend", "Business fires", "For businesses, our accountants calculate your business interruption loss as well."),
        ],
        "covers_head": "What a fire claim can include",
        "covers_intro": "Depending on your policy, a fire claim can cover far more than people expect. These are the areas we check for every client.",
        "covers": [
            ("Rebuilding and repairs", "Restoring the structure, roof, walls, floors, kitchen and bathrooms to their condition before the fire."),
            ("Smoke and soot damage", "Specialist cleaning of surfaces, soft furnishings and ventilation. Soot can damage surfaces if it isn't dealt with properly."),
            ("Water damage from firefighting", "Drying out and repairing damage caused by the water used to put the fire out."),
            ("Contents", "Replacing or restoring furniture, clothing, electrical items and personal belongings."),
            ("Alternative accommodation", "Somewhere for you and your family to live while your home can't be lived in."),
            ("Business losses", "For commercial claims, stock, equipment and loss of income through business interruption cover."),
        ],
        "cases": [HOUSE_FIRE, FACTORY_FIRE],
        "faqs": [
            ("Can I go back into my home after a fire?",
             "<p>Only when the fire service tells you it's safe. Even then, take care: there may be structural damage, and smoke and soot can be hazardous. If you need to collect essentials, ask the fire service or your loss assessor first.</p>"),
            ("Will my insurer pay for somewhere to stay?",
             "<p>Many home insurance policies include alternative accommodation if your home can't be lived in. We check what your policy covers and arrange suitable accommodation for you.</p>"),
            ("Should I throw away smoke-damaged belongings?",
             "<p>No. Keep damaged items until your insurer has agreed they can be disposed of, because they're evidence of your loss. Photograph everything before anything is moved or cleaned.</p>"),
            ("The insurer is investigating the cause of the fire. What does that mean?",
             "<p>For larger fires, insurers often investigate the cause to confirm the loss is covered by your policy. It's a normal part of the process, but it can feel intrusive. Your loss assessor represents you throughout and makes sure your account is clear and accurate.</p>"),
            ("How long does a fire claim take?",
             "<p>Every claim is different. A straightforward claim can settle in a matter of weeks, while a major fire involving rebuilding can take considerably longer. We progress your claim as quickly and forcefully as we can, and we don't get paid until you do.</p>"),
        ],
        "related": ["flood.html", "escape.html", "home-claims.html", "bi.html"],
        "advice": ("advice.html#after-a-fire", "What to do after a fire: our step-by-step checklist"),
    },
    # ------------------------------------------------------------------ flood
    {
        "key": "flood.html",
        "route": "flood-damage-claims/",
        "crumb": "Flood damage claims",
        "title": "Flood Damage Insurance Claims | Independent Claims Consultants",
        "desc": "Loss assessors for flood damage claims. We manage drying, repairs and your flood insurance claim for homes and businesses, and negotiate with your insurer.",
        "pill": "Flood damage claims",
        "h1": "Flood damage <span>insurance claims</span>",
        "lead": "Flood water can damage almost everything it reaches. We take your flood insurance claim off your hands, from drying out your property to negotiating a fair settlement with your insurer.",
        "image": ("water-damage", "Standing water across the floor of an empty room"),
        "claim": "Flood",
        "service_type": "Flood damage insurance claims",
        "icon": "flood",
        "intro_head": "You don't have to deal with a flood claim alone",
        "intro": [
            "Following a flood, you have to prepare a complicated insurance claim, engage and oversee contractors and negotiate with your insurance company, often while living somewhere else. It's a lot to take on at a difficult time.",
            "When you appoint us, a dedicated loss assessor manages the whole process. We make sure your property is thoroughly dried and sanitised by an experienced restoration company, so problems such as damp and dry rot don't appear later, and that your claim reflects the full extent of the damage.",
            "Flood damage is often worse than it first looks. Water soaks into floors, walls and insulation, and contaminated flood water means many materials and belongings can't simply be cleaned. We make sure nothing is overlooked.",
        ],
        "help_head": "How we help with your flood claim",
        "help": [
            ("droplet", "Proper drying", "Professional drying, with moisture readings to confirm the building is dry before repairs start."),
            ("home", "Alternative accommodation", "Somewhere to stay while your home is dried and repaired, where your policy covers it."),
            ("file", "Buildings and contents", "A complete, well-evidenced list of everything that's been damaged."),
            ("scale", "Negotiation", "We deal with the insurer and its loss adjuster on your behalf."),
            ("tool", "Reinstatement", "We appoint and supervise contractors to put your property right."),
            ("trend", "Business floods", "Stock, equipment and business interruption losses for commercial clients."),
        ],
        "covers_head": "What a flood claim can include",
        "covers_intro": "Depending on your policy, these are the areas we look at on every flood claim.",
        "covers": [
            ("Emergency work and strip-out", "Pumping out water and removing damaged flooring, plaster and fittings."),
            ("Drying and sanitising", "Professional drying and cleaning, especially important where flood water is contaminated."),
            ("Repairs and reinstatement", "Replastering, flooring, kitchens, electrics and decoration."),
            ("Contents", "Furniture, appliances and belongings damaged by the water."),
            ("Alternative accommodation", "Somewhere to live while the work is carried out."),
            ("Business interruption", "For businesses, lost income while your premises are restored."),
        ],
        "cases": [RETAIL_FLOOD],
        "faqs": [
            ("What's the difference between flood and escape of water?",
             "<p>Flood usually means water entering from outside, such as overflowing rivers, surface water after heavy rain or the sea. Escape of water means water leaking from inside the property, such as a burst pipe or a leaking appliance. Policies treat them differently, so it's important the claim is made under the right section.</p>"),
            ("How long does it take to dry a flooded home?",
             "<p>It depends on how much water got in, how long it stayed and what the building is made of. It's often several weeks. Repairs shouldn't start until moisture readings show the building is dry, otherwise problems like damp and mould can follow.</p>"),
            ("Does my home insurance cover flooding?",
             "<p>Most standard buildings and contents policies in the UK include flood cover, but there can be exclusions and higher excesses, particularly in areas that have flooded before. We review your policy and explain what it covers.</p>"),
            ("Should I start cleaning up straight away?",
             "<p>Make the property safe and stop further damage if you can, but photograph and video everything first. Don't throw damaged items away until your insurer has seen them or agreed, and keep receipts for any emergency costs.</p>"),
        ],
        "related": ["escape.html", "fire.html", "home-claims.html", "commercial.html"],
        "advice": ("advice.html#after-a-flood", "What to do after a flood or leak: our step-by-step checklist"),
    },
    # ------------------------------------------------------------------ escape of water
    {
        "key": "escape.html",
        "route": "escape-of-water-claims/",
        "crumb": "Escape of water claims",
        "title": "Escape of Water Claims | Independent Claims Consultants",
        "desc": "Loss assessors for escape of water claims: burst pipes, leaks and water ingress. We find the full extent of the damage and negotiate your settlement.",
        "pill": "Escape of water claims",
        "h1": "Escape of water <span>and leak claims</span>",
        "lead": "Burst pipes, leaking appliances and water ingress can cause far more damage than you can see. We make sure your claim covers all of it, and deal with your insurer for you.",
        "image": ("repairs-plaster", "A gloved hand plastering a wall during repairs"),
        "claim": "Escape of water or leak",
        "service_type": "Escape of water insurance claims",
        "icon": "droplet",
        "intro_head": "The damage you can't see matters most",
        "intro": [
            "Escape of water is one of the most common types of home insurance claim. A burst pipe, a failed washing machine hose or a leaking tank can soak floors, ceilings and walls before anyone notices.",
            "Water travels under floors and behind walls, and the damage isn't always visible straight away. If it isn't found and dried properly, it can lead to damp, mould and repeat repairs later on.",
            "Our loss assessors make sure the full extent of the damage is identified and included in your claim, that the property is properly dried before repairs start, and that you're treated fairly by your insurer.",
        ],
        "help_head": "How we help with your escape of water claim",
        "help": [
            ("droplet", "Find all the damage", "We make sure hidden damage under floors and behind walls is found and included."),
            ("file", "Trace and access", "Many policies cover the cost of finding the leak and putting right the damage caused to reach it."),
            ("shield", "Proper drying", "Repairs only start once moisture readings confirm the building is dry."),
            ("home", "Alternative accommodation", "Somewhere to stay if your home can't be lived in, where your policy covers it."),
            ("scale", "Negotiation", "We deal with your insurer and its loss adjuster on your behalf."),
            ("tool", "Repairs overseen", "We appoint and supervise contractors through to completion."),
        ],
        "covers_head": "Common causes of escape of water",
        "covers_intro": "These are the situations we help with most often. Whether a particular cause is covered depends on your policy, so it's worth asking us to check.",
        "covers": [
            ("Burst or frozen pipes", "Often sudden and serious, especially in cold weather or in empty properties."),
            ("Leaking appliances", "Washing machines, dishwashers, fridges and their hoses and connections."),
            ("Tanks and heating systems", "Leaking cold water tanks, cylinders, radiators and boilers."),
            ("Bathrooms and showers", "Leaks from baths, showers and toilets. Some policies treat gradual leaks differently from sudden ones."),
            ("Water ingress", "Water getting into the building and causing damage to the structure and contents."),
            ("Damage to flats below", "Leaks that affect neighbouring properties, which can involve more than one insurer."),
        ],
        "cases": [],
        "faqs": [
            ("What does trace and access mean?",
             "<p>Trace and access is cover for the cost of finding the source of a leak and then repairing the damage caused while getting to it, such as lifting floors or opening walls. Many home insurance policies include it, sometimes with a limit. We check your policy and make sure it's claimed.</p>"),
            ("Is a leaking shower covered?",
             "<p>It depends on your policy. Many policies treat sudden escapes of water differently from damage caused gradually over time, such as a slow leak from worn seals. The wording matters, so it's worth asking us to review it before you accept a decision.</p>"),
            ("Why is my excess higher for escape of water?",
             "<p>Many insurers set a higher excess for escape of water claims than for other claims. Your policy schedule shows the amount. We make sure it's applied correctly to your claim.</p>"),
            ("What should I do first?",
             "<p>Turn off the water at the stopcock, switch off electrics in affected areas if it's safe to do so, and photograph the damage. Then tell your insurer and contact us as early as you can.</p>"),
        ],
        "related": ["flood.html", "home-claims.html", "landlords.html", "fire.html"],
        "advice": ("advice.html#after-a-flood", "What to do after a flood or leak: our step-by-step checklist"),
    },
    # ------------------------------------------------------------------ business interruption
    {
        "key": "bi.html",
        "route": "business-interruption-claims/",
        "crumb": "Business interruption claims",
        "title": "Business Interruption Claims | Independent Claims Consultants",
        "desc": "Specialist loss assessors for business interruption claims. Our forensic and consequential loss accountants calculate your lost income and protect your business.",
        "pill": "Business interruption claims",
        "h1": "Business interruption <span>claims</span>",
        "lead": "When damage stops your business trading, every week counts. Our specialists calculate your loss accurately and fight for the settlement that keeps your business going.",
        "image": ("business-warehouse", "Aisle of a warehouse with stock on tall orange racking"),
        "claim": "Business interruption",
        "who": "Business",
        "service_type": "Business interruption insurance claims",
        "icon": "trend",
        "intro_head": "Specialist help for complex claims",
        "intro": [
            "Business interruption claims are rarely simple. They involve your accounts, your trading history and assumptions about how your business would have performed if the damage hadn't happened. The loss adjusters and forensic accountants appointed by insurers often present them in a way that makes them more complex still.",
            "Our team includes forensic and consequential loss accountants who work through those complexities for you. While your premises are being restored, they calculate your business interruption claim accurately to protect your organisation against financial loss.",
            "We also take an active role in reducing the impact the incident has on your business, so you can recover and get trading again as soon as possible.",
        ],
        "help_head": "How we help with your business interruption claim",
        "help": [
            ("calc", "Accurate calculations", "Forensic and consequential loss accountants calculate your loss of income."),
            ("trend", "Increased costs", "Extra costs of keeping the business running, such as temporary premises."),
            ("file", "Evidence and records", "We assemble the accounts and records the insurer needs to see."),
            ("scale", "Negotiation", "We deal with the insurer's loss adjuster and accountants on your behalf."),
            ("briefcase", "Back to trading", "We work to get you operational again as quickly as possible."),
            ("check", "Ready for liability", "Everything in place for the moment your insurer accepts liability."),
        ],
        "covers_head": "Key terms in a business interruption claim",
        "covers_intro": "Business interruption policies use their own language. These are the terms you're most likely to come across.",
        "covers": [
            ("Loss of gross profit or revenue", "The income your business loses because the damage stopped or reduced trading."),
            ("Increased cost of working", "Extra spending to keep the business going and reduce the loss, such as temporary premises or equipment."),
            ("Indemnity period", "The maximum length of time your policy will pay for, starting from the date of the damage."),
            ("Sum insured", "The most your policy will pay. If it's too low, your settlement can be reduced."),
            ("Policy extensions", "Some policies extend cover to situations such as damage at a supplier or loss of access to your premises."),
            ("Material damage", "Usually, the interruption must be caused by damage that's covered under your property insurance."),
        ],
        "cases": [FACTORY_FIRE, RETAIL_FLOOD],
        "faqs": [
            ("What does business interruption insurance cover?",
             "<p>It's designed to put your business back in the financial position it would have been in if the damage hadn't happened. Typically that means lost gross profit or revenue during the indemnity period, plus the increased cost of working to keep the business going. Exactly what's covered depends on your policy.</p>"),
            ("What is an indemnity period?",
             "<p>It's the maximum period your insurer will pay business interruption losses for, starting from the date of the damage. If recovery takes longer than the indemnity period, losses after it ends aren't covered, which is why it's important to understand yours early.</p>"),
            ("What information will I need?",
             "<p>Usually your recent accounts, management figures, trading records and evidence of extra costs. Our accountants tell you exactly what's needed and help you put it together.</p>"),
            ("Can you help if my business interruption claim has been rejected?",
             "<p>Yes. A rejection doesn't mean the insurer is right. We review the policy wording and the reasons given, and fight for the claim to be accepted and settled.</p>"),
        ],
        "related": ["commercial.html", "fire.html", "flood.html", "landlords.html"],
        "advice": None,
    },
    # ------------------------------------------------------------------ homeowners hub
    {
        "key": "home-claims.html",
        "route": "domestic-insurance-claim/",
        "crumb": "Home insurance claims",
        "title": "Home Insurance Claims | Independent Claims Consultants",
        "desc": "Loss assessors for homeowners. We manage your home insurance claim for fire, flood, escape of water, storm and theft damage, and negotiate with your insurer.",
        "pill": "Home insurance claims",
        "h1": "Home insurance claims <span>handled for you</span>",
        "lead": "After a fire, flood, leak or break-in at your home, we take the insurance claim off your hands and work to get you back home as quickly as possible.",
        "image": ("homes-terrace", "Victorian terraced houses on a street in Oxford"),
        "who": "Homeowner",
        "service_type": "Home insurance claims",
        "icon": "home",
        "intro_head": "Support when it matters most",
        "intro": [
            "Much like any major incident at your home, the aftermath of a theft or any kind of damage can have a significant emotional impact on you and your family. Coupled with the stress of dealing with an insurance claim, it's a lot to cope with.",
            "That's why so many homeowners and landlords turn to us. Our loss assessors are experts in handling all property claims, and every client is assigned a dedicated loss assessor who runs the claim smoothly and efficiently.",
            "Your insurer's loss adjuster assesses the claim for the insurer. We work only for you, making sure the full extent of the damage to your buildings and contents is identified and that you receive everything you're entitled to.",
        ],
        "help_head": "What we do for homeowners",
        "help": [
            ("shield", "Emergency help", "We secure your home and organise urgent works."),
            ("home", "Alternative accommodation", "Somewhere to stay while your home is put right, where your policy covers it."),
            ("file", "Buildings and contents", "We identify the full extent of the damage to both."),
            ("droplet", "Drying and sanitising", "Thorough drying so damp and dry rot don't follow."),
            ("scale", "Negotiation", "We negotiate your settlement with the insurer and its adjuster."),
            ("tool", "Repairs overseen", "We appoint and supervise surveyors and contractors."),
        ],
        "covers_head": "Home insurance claims we handle",
        "covers_intro": "Whatever has happened at your home, we can help. These are the claims we handle most often.",
        "covers": [
            ("Fire and smoke damage", "From kitchen fires to serious house fires, including smoke, soot and firefighting water damage."),
            ("Flood", "Damage from rivers, surface water and heavy rain."),
            ("Escape of water", "Burst pipes, leaking appliances and water ingress."),
            ("Storm damage", "Damage to roofs, walls and contents from high winds and heavy rain."),
            ("Theft and burglary", "Stolen belongings and damage caused by a break-in."),
            ("Subsidence and impact", "Ground movement, and damage from vehicles or falling objects."),
        ],
        "cases": [HOUSE_FIRE],
        "faqs": [
            ("Do I need a loss assessor if my insurer is dealing with the claim?",
             "<p>Your insurer appoints a loss adjuster to assess the claim on its behalf, not yours. A loss assessor gives you your own expert representation, so you're on an equal footing and nothing you're entitled to is missed.</p>"),
            ("Will I have to move out while repairs are done?",
             "<p>If your home can't be lived in, many policies cover alternative accommodation. We check your cover and arrange somewhere suitable for you and your family.</p>"),
            ("What if I'm underinsured?",
             "<p>Underinsurance can reduce your settlement, sometimes severely. It's more common than people think. If you're worried about it, speak to us as soon as possible.</p>"),
            ("How much does it cost?",
             "<p>Your first consultation is free and there's no obligation. We work on a no win, no fee basis, so we don't get paid until you do.</p>"),
        ],
        "related": ["fire.html", "flood.html", "escape.html", "landlords.html"],
        "advice": ("advice.html", "Practical guides in our advice centre"),
    },
    # ------------------------------------------------------------------ commercial hub
    {
        "key": "commercial.html",
        "route": "commercial-claims/",
        "crumb": "Commercial claims",
        "title": "Commercial Insurance Claims | Independent Claims Consultants",
        "desc": "Loss assessors for businesses. We manage commercial fire, flood and business interruption claims to protect your cash flow and get you trading again.",
        "pill": "Commercial claims",
        "h1": "Commercial insurance claims <span>for businesses</span>",
        "lead": "No matter what has caused the damage at your business, we make sure you stay in control of the insurance claim and safeguard your company's future.",
        "image": ("business-stock", "Warehouse interior with goods on shelving"),
        "who": "Business",
        "service_type": "Commercial property insurance claims",
        "icon": "building",
        "intro_head": "Protecting your business and your cash flow",
        "intro": [
            "A fire or flood at your commercial premises can put your whole business at risk. You have to manage a complicated insurance claim while trying to fulfil existing orders, keep your customers and get the business fully functioning again.",
            "Your insurer won't pay anything until it's satisfied it's liable and that you've met all the conditions of your policy. Delays in getting liability accepted can have a dramatic effect on cash flow.",
            "We provide a complete claims management service. Your dedicated specialist commercial loss assessor works on your behalf to get you operating again as quickly as possible, with everything in place ready for the moment liability is accepted.",
        ],
        "help_head": "What we do for businesses",
        "help": [
            ("fire", "Commercial fire and flood", "Complete claims management for damaged premises."),
            ("trend", "Business interruption", "Forensic and consequential loss accountants calculate your lost income."),
            ("box", "Stock and machinery", "We make sure damaged stock and equipment are fully valued."),
            ("check", "Ready for liability", "Everything prepared for the moment your insurer accepts liability."),
            ("scale", "Legal specialists", "Expert support when an insurer resists your claim."),
            ("briefcase", "Back to trading", "We work to get you operational again as quickly as possible."),
        ],
        "covers_head": "Commercial claims we handle",
        "covers_intro": "We represent businesses of all sizes, from shops and offices to factories and warehouses.",
        "covers": [
            ("Commercial fire", "Damage to premises, stock and equipment, plus the effect on trading."),
            ("Commercial flood", "Flood and water damage to business premises and stock."),
            ("Business interruption", "Loss of income and increased costs while you recover."),
            ("Stock and machinery", "Valuing and claiming for damaged stock, plant and equipment."),
            ("Theft", "Stolen stock and equipment, and damage caused by a break-in."),
            ("Refused or disputed claims", "Representation when an insurer is reluctant to pay."),
        ],
        "cases": [FACTORY_FIRE, RETAIL_FLOOD],
        "faqs": [
            ("How quickly can you get involved?",
             "<p>As early as possible. The start of your claim is when your insurer appoints its loss adjuster, so it's the best time for you to have your own representation too.</p>"),
            ("Can you help with business interruption as well as property damage?",
             "<p>Yes. Our forensic and consequential loss accountants calculate your business interruption claim while the property damage is being dealt with, so both parts of your claim are covered.</p>"),
            ("My insurer has refused the claim. Can you help?",
             "<p>Yes. A refusal doesn't mean the insurer is right. We've helped businesses whose claims were initially refused go on to obtain excellent settlements.</p>"),
            ("How much does it cost?",
             "<p>Your first consultation is free and there's no obligation. We work on a no win, no fee basis, so we don't get paid until you do.</p>"),
        ],
        "related": ["bi.html", "fire.html", "flood.html", "landlords.html"],
        "advice": None,
    },
    # ------------------------------------------------------------------ landlords hub
    {
        "key": "landlords.html",
        "route": "landlord-insurance-claims/",
        "crumb": "Landlord insurance claims",
        "title": "Landlord Insurance Claims | Independent Claims Consultants",
        "desc": "Loss assessors for landlords. We handle your landlord insurance claim, the repairs and your loss of rent after fire, flood or escape of water damage.",
        "pill": "Landlord insurance claims",
        "h1": "Landlord insurance claims <span>and loss of rent</span>",
        "lead": "When a property you let is damaged, you're dealing with tenants, lost rent and your insurer all at once. We handle the claim and the reinstatement so the property can be let again.",
        "image": ("landlord-flats", "Red-brick Victorian mansion block of flats in London"),
        "who": "Landlord",
        "service_type": "Landlord insurance claims",
        "icon": "key",
        "intro_head": "Protecting your rental income",
        "intro": [
            "Damage to a let property brings its own pressures. Your tenants may need somewhere else to live, your rental income stops, and your insurer needs to be satisfied before it pays anything.",
            "We take the claim off your hands. Your dedicated loss assessor deals with the insurer and its loss adjuster, makes sure the full extent of the damage is claimed for, and includes your loss of rent where your policy covers it.",
            "With our legal team and associate building company, we can manage the whole process through to a refurbished property that's ready to let again.",
        ],
        "help_head": "What we do for landlords",
        "help": [
            ("pound", "Loss of rent", "We claim for the rent you lose while the property can't be let, where your policy covers it."),
            ("users", "Multi-tenancy properties", "Experience with complex buildings and several tenants."),
            ("tool", "Reinstatement", "Our associate building company can carry out the repairs."),
            ("file", "Buildings and landlord's contents", "Everything you're responsible for as the landlord."),
            ("scale", "Negotiation", "We deal with the insurer so you don't have to."),
            ("shield", "Emergency works", "We secure the property and arrange urgent repairs."),
        ],
        "covers_head": "Landlord claims we handle",
        "covers_intro": "Whether you let a single flat or manage a block, we can help with:",
        "covers": [
            ("Fire", "Including fires in multi-occupancy buildings."),
            ("Flood and escape of water", "Including leaks that affect more than one flat."),
            ("Storm damage", "Damage to roofs, walls and communal areas."),
            ("Malicious damage", "Damage caused deliberately to the property."),
            ("Loss of rent", "Rental income lost while the property can't be let."),
            ("Alternative accommodation for tenants", "Where your landlord policy includes it."),
        ],
        "cases": [MULTI_TENANCY_FIRE],
        "faqs": [
            ("Does landlord insurance cover loss of rent?",
             "<p>Many landlord policies include loss of rent if the property can't be let because of insured damage, often up to a set limit or period. We check your policy and make sure it's included in your claim.</p>"),
            ("Who is responsible for the tenants' belongings?",
             "<p>Usually tenants need their own contents insurance for their belongings. Your landlord policy normally covers the building and any contents you provide as the landlord.</p>"),
            ("Can you help with a block of flats?",
             "<p>Yes. We have experience with multi-tenancy properties, where a claim can affect several tenants and sometimes more than one insurer.</p>"),
            ("How much does it cost?",
             "<p>Your first consultation is free and there's no obligation. We work on a no win, no fee basis, so we don't get paid until you do.</p>"),
        ],
        "related": ["fire.html", "escape.html", "commercial.html", "home-claims.html"],
        "advice": None,
    },
]

# Short labels and descriptions used when linking to these pages from elsewhere
CARD = {
    "fire.html": ("fire", "Fire damage claims", "Fire, smoke and soot damage at homes and businesses."),
    "flood.html": ("flood", "Flood damage claims", "Damage from rivers, surface water and heavy rain."),
    "escape.html": ("droplet", "Escape of water claims", "Burst pipes, leaks and water ingress."),
    "bi.html": ("trend", "Business interruption", "Lost income and extra costs while you recover."),
    "home-claims.html": ("home", "Home insurance claims", "Everything we do for homeowners."),
    "commercial.html": ("building", "Commercial claims", "Claims for shops, offices, factories and warehouses."),
    "landlords.html": ("key", "Landlord claims", "Repairs, tenants and loss of rent."),
}
